server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&timeZone=utc
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
mybatis-plus:
  global-config:
    dbConfig:
      tablePrefix: tb_
  type-aliases-package: com.ouest.user.pojo
logging:
  level:
    com.ouest: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka