server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&timeZone=utc
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:80
      discovery:
        cluster-name: HZ
#      discovery:
#        cluster-name: HZ
mybatis-plus:
  global-config:
    dbConfig:
      tablePrefix: tb_
  type-aliases-package: com.ouest.order.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ouest: info # only debug level can the feign log level work
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
#feign:
#  client:
#    config:
#      userservice:
#        loggerLevel: FULL
